task 03-SFC, 04-vue-cli
js-tasks-ru/vue-20221107_viktor-vasiuk pull request #4
Opened 2022-11-23 15:20 UTC by vivask

https://github.com/js-tasks-ru/vue-20221107_viktor-vasiuk/blob/master/04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
Два теста в задаче 04/03-UiDropDown1 сваливаются по ошибке, сложно понять что не так.
Подскажите, пожалуста, в каком направлении искать.
Спасибо!

2022-11-23 15:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-24 05:48 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-11-24 05:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-11-24 06:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-11-24 14:17 UTC, ShGKme requested changes
В `04-vue-cli/02-TheToaster` отличное решение в JS части, но получилось неудачное разделение на компоненты...

В `04-vue-cli/03-UiDropdown1` требуется более "vue-way" решение с заменой ручного отслеживания и управлением данными компонентами на вычисляемые свойства.

Также на мой взгляд лучше перенести все классы в шаблон и лишь описывать условиях их добавления вместо их вычисления в JS.

2022-11-24 14:17 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
>      </div>
Выделение тоста в компонент `UiToast` получилось не очень удачным, разрывающим тост.
1. Компонент `UiToast` не самостоятельный. Чтобы его использовать для вывода тоста, надо его обернуть в див и добавить при использовании стили этого тоста.
2. Хотя сам компонент имеет слот для передачи текста тоста, здесь он используется только для вывода иконки тоста.

Если выделять компонент `UiToast`, то должно быть возможно его использовать, как самостоятельный компонент. В нём должна быть вся разметка тоста и все стили одного тоста.

2022-11-24 14:17 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  },
Во Vue, когда требуется добавить класс по условию, удобно использовать синтаксис привязки класса объектом, где ключ - имя класса, а значение - флаг добавления класса.

[https://vuejs.org/guide/essentials/class-and-style.html#class-and-style-bindings](https://vuejs.org/guide/essentials/class-and-style.html#class-and-style-bindings)

Так явно видно, от чего зависит наличие каждого класса, в привычном для Vue разработчиков стиле и удобно добавлять новые классы при необходимости.

2022-11-24 14:17 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
Многие из этих свойств не являются самостоятельными данными компонента. Они вычисляются на основе входных параметров и всегда одинаковыми вычислениями обновляются при изменении входных параметров.

Лучше их явно делать именно вычисляемыми свойствами. Тогда не потребуется думать, за чем именно нужно следить и когда обновлять вычисляемое значение, а будет явное решение, гед сами свойства описаны, как вычисляющиеся.

Собственное состояние компонента - `openedDropdown`. Компонент сам независимо управляет своим открытием.

Немного сложнее со свойством `selected`, потому что он меняется через `v-model`. Так как реакция на изменение на `<select>` уже реализовано через `@change="change($event)"`, то `v-model="selected"` можно заменить на `:value="modelValue"`

2022-11-24 14:17 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Аналогично первой задачи блока, лучше в шаблоне описать, какие классы и от чего зависят. Так будет проще добавлять новые классы, а в шаблоне будет сразу видно вёрстку без необходимости уходить в JS часть, чтобы увидеть классы блока.

2022-11-24 14:17 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +          this.toggleIcon = 'dropdown__toggle_icon';
Аналогично с этими свойствами. Вместо хранения в них классов, лучше классы оставить в шаблоне, а вычислять лишь данные, которые определяют необходимость добавления этих классов. Флаг наличия иконок.

2022-11-25 13:39 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-11-25 21:24 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-11-25 21:24 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +      return false;
Здесь можно использовать метод `some`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2022-11-25 21:24 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
>      },
А здесь отлично подходит метод `find`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

Кстати, чтобы не делать поиск два раза, можно в вычисляемом свойстве найти целиком объект `option`, а уже потом доставать из него всё необходимое

2022-11-25 21:25 UTC, merged