task 06-wrappers
js-tasks-ru/vue-20221107_viktor-vasiuk pull request #6
Opened 2022-12-05 05:56 UTC by vivask

По задаче 5 приложил свое решение https://github.com/vivask/vue-20221107_viktor-vasiuk/blob/master/06-wrappers/05-UiImageUploader/components/UiImageUploader.vue.my, не все тесты проходят.
По задаче 6 запись :model-value="value" самостоятельно нигде не нашел и в лекции видимо упустил,  решение через v-model и valueAsNumber не срослось).

2022-12-05 06:11 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-12-05 06:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-05 06:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-12-06 04:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-06 05:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-12-06 05:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-06 10:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-12-06 17:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-06 17:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-12-07 22:44 UTC, ShGKme commented on 06-wrappers/02-UiButton/components/UiButton.vue
> +    ]"
Класс `button_danger` есть всегда

2022-12-07 22:44 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +  },
`mounted` не подходит для синхронной инициализации состояния. Он вызывается уже после того, как компонент отрендерился на странице с тем, что было и только потом вычисляет начальные значения, чтобы отрендерить всё ещё раз уже корректно. В таких случаях нужно использовать `created`.

2022-12-07 22:44 UTC, ShGKme commented on 07-forms/04-GeneratedForm/components/MeetupAgendaItemForm.vue
> +      ></component>
Здесь можно не делать копию объекта, просто передавая все параметры.

2022-12-07 22:44 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue.my
> +      <span class="image-uploader__text">{{ text }}</span>
Так же, как в прошлых местах с выводом картинки фоном через переменную, здесь добавлять стиль с картинкой нужно только, если эта картинка есть. Иначе получается некорректный стиль, который ломает отображение картинки по умолчанию.

2022-12-07 22:44 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue.my
> +    },
Класс `image-uploader__preview` не нужно вычислять, он всегда есть у элемента. Обычные классы вёрстки лучше оставлять в разметке, чтобы лучше было видно вёрстку. А для классов, появляющихся по условию - использовать синтаксис привязки объектом, где сразу можно описать условие добавление каждого класса и легко добавлять новые классы. Это также можно сделать в шаблоне, чтобы лучше видеть вёрстку, не уходя в JS.

2022-12-07 22:44 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue.my
> +      },
Компонент не знает, как именно работает загрузчик и что придёт после загрузки. Он должен только выполнить загрузку и отдать то, что пришло, с событием `upload`. Мы не знаем, есть ли там объект, есть ли в нём поле `image`.

2022-12-07 22:44 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue.my
> +    },
Решение через computed с геттером и сеттером усложняет понимание решение. В нём не требуется именно свойства, в с которым можно работать через получение и изменение значения, как при привязке свойства в `v-model`. Есть отдельные задачи - показать текущее изображение и обработать разнообразные изменения изображения. При этом изменения могут быть очень разные:
1. Удаление
2. Успешная загрузка
3. Простой выбор

Разбирать эти случаи гораздо удобнее, если это разные функции или просто разный код, а не вариации присваивания. Например, если загрузчик ничего не вернёт с API при успешной загрузки, сеттер решит, что это удаление.

2022-12-07 22:44 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue.my
> +    },
Отображать картинку через `URL.createObjectURL(file);` требуется всегда, независимо от того, есть ли загрузчик. Как только картинка выбрана - всё. Мы её имеем и можем показать её в компоненте. Её не требуется загружать для отображения.

2022-12-07 22:44 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue.my
> +      },
`preview` по схеме состояний компонента нужен при инициализации. Когда пользователь ещё не начал работать с компонентом, но уже нужно показать, какая картинка была выбрана когда-то ранее при изменении изображения.

Как только пользователь выбирает новую картинку или удаляет её, компонент уже сам может знать, что именно выводить.

По этой причине требуется хранить текущую картинку в состоянии компонента, а `preview` использовать только для инициализации этого состояния.

2022-12-07 22:51 UTC, ShGKme requested changes
Все решённые задачи приняты, но нужно обновить решение UiImageUploader

2022-12-07 22:53 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue.my
> +      },
Добавлю, что именно такое решение по интерфейсу компонента может быть спорным, и может быть удобнее иметь `preview`, который обновляется с `v-model`. Но тогда пользователю компонента потребуется использовать параметр `preview`, даже если никакой "старой картинки" ему не нужно. В этом случае пользователь компонента будет ожидать, что компонент "просто работает".

2022-12-08 04:29 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-12-08 13:11 UTC, ShGKme approved these changes

2022-12-08 13:12 UTC, merged