task 08-reactivity & task 09-rendering
js-tasks-ru/vue-20221107_viktor-vasiuk pull request #7
Opened 2022-12-14 05:31 UTC by vivask

2022-12-14 05:33 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-12-14 20:55 UTC, ShGKme requested changes
В `08-reactivity/05-reactify/` есть некорректное (и лишнее) использование `ref` и `watch`.

2022-12-14 20:55 UTC, ShGKme commented on 08-reactivity/05-reactify/utils/reactify.js
> +        },
Вместо `isRef(item) ? item.value : item` можно использовать более простую утилиту `unref(item)`, которая делает тоже самое и нужна как раз тогда, когда не известно, является ли значение реактивным.

2022-12-14 20:55 UTC, ShGKme commented on 08-reactivity/05-reactify/utils/reactify.js
> +    });
`watch` внутри вычисления `computed` лишний. Так при каждом вычислении вычисляемого значения будет создаваться новое отслеживание через `watch`. При этом сам `watch` здесь реализован, как вычисляемое значение для вычисления `array` от `args`, и лучше бы было реализовано, как `computed`, если бы было необходимо. Но этот `watch` даже не будет работать, так как `r` от которого он зависит - никогда не меняется. Он только при инициализации берёт значение `args`.

Но в итоге всё работает, потому что работает за счёт `computed`, который всё это делает при изменении аргументов, так как зависит от них.

2022-12-14 20:55 UTC, ShGKme commented on 06-wrappers/02-UiButton/components/UiButton.vue
>      ]"
У кнопки не должно быть постоянного класса `button_danger`. Только для варианта `danger`.

2022-12-15 05:35 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-12-15 09:56 UTC, ShGKme approved these changes
Все задачи приняты

2022-12-15 09:57 UTC, merged